### ISSUE TITLE
liblcd1602i2c.so File

### ISSUE THREAD

**Issue by mbazzo** [laheller/RPI_Peripheral#1]
Would you have this file? liblcd1602i2c.so
I do not know much about c / c ++

Tks

**Comment by laheller** [comment]
Hello @mbazzo 

You don't need to know the c/c++
Just check the readme of this repo.
You have to install needed packages, including monodevelop, then open solution (.sln file in monodevelop IDE) and build it.
When build passes, it will automatically create and install **liblcd1602i2c.so** library.

BR,

Ladislav
